services:
  - type: web
    name: emotion-analyzer-api
    runtime: docker
    repo: https://github.com/kalyan20004/emotion-analyzer
    plan: free
    rootDir: Sentiment # Specify the root directory where your code is located
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://kalyan:${MONGO_PASSWORD}@cluster0.5dyy5f8.mongodb.net/?retryWrites=true&w=majority&tls=true&tlsInsecure=false&appName=Cluster0"
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: DB_NAME
        value: emotion_analyzer
      - key: MODEL_HF_PATH
        value: NNKalyan/emotion-analyzer-model
      - key: USE_LOCAL_MODEL
        value: "False"
      - key: HF_TOKEN
        sync: false
    healthCheckPath: /health
    # Increase timeout for health checks
    autoDeploy: true
